import { PageSchema } from "@/components/constructor/page-render/types";
import { COMPANY_NAME } from "@/resources/constants";

const schema: PageSchema = {
    meta: {
        title: `${COMPANY_NAME} — Create a Business Plan in 24h or Instantly with AI`,
        description: `${COMPANY_NAME} helps entrepreneurs, startups, and students create stunning business plans — written by real experts in 24 hours or instantly generated by our smart AI assistant.`,
        keywords: [
            "business plan",
            "startup plan",
            "AI business generator",
            "pitch deck",
            "financial forecast",
            "startup strategy",
            "entrepreneur tools",
            "small business support",
        ],
        canonical: "/",
        ogImage: {
            title: COMPANY_NAME,
            description: `Turn your idea into a complete business plan — in 24h or instantly with AI.`,
            bg: "#0a2540",
            color: "#ffffff",
        },
    },

    blocks: [
        // 🏁 HERO — Dual Offer
        {
            type: "custom",
            component: "HeroSection",
            title: "Turn Your Idea into a Business Plan",
            highlight: "Written by Experts or Instantly with AI — You Choose",
            description: `${COMPANY_NAME} helps you bring your business idea to life in minutes. Choose to have your plan written by professional analysts within 24 hours, or instantly generated by AI. No stress, no complex templates — just results.`,
            primaryCta: { text: "Get Expert Plan (24h)", link: "/profile" },
            secondaryCta: { text: "Try AI Generator", link: "/profile" },
            image: "image1",
            align: "right",
            showTrustBadge: true,
        },

        {
            type: "custom",
            component: "HighlightStrip",
            items: [
                { image: "logo1", text: "Eleven Labs" },
                { image: "logo2", text: "Zilliz" },
                { image: "logo3", text: "Nexora" },
                { image: "logo4", text: "Quantara Solutions" },
                { image: "logo5", text: "BitNova" },
                { icon: "⚡", text: "Fast & Reliable" },
            ],
        },

        // 🧠 SECTION — Human vs AI
        {
            type: "section",
            title: "Human Expertise Meets AI Speed",
            description:
                "Whether you need a plan crafted by professionals or want to generate one instantly with AI — our platform combines human insight with machine precision to fit your goals and timeline.",
            left: {
                type: "custom",
                component: "InfoBlock",
                title: "Expert-Written Plan in 24 Hours",
                description:
                    "Need a business plan that investors will trust? Our team of experienced business analysts creates a personalized document with strategy, market research, and 3-year financial projections — ready in just one day.",
                image: "image2",
                bullets: [
                    "Written by real business professionals",
                    "Delivered within 24 hours",
                    "Includes marketing, competitor & financial sections",
                    "Provided in editable PDF and DOCX formats",
                ],
            },
            right: {
                type: "custom",
                component: "InfoBlock",
                title: "AI Instant Generator",
                description:
                    "Short on time? Let our AI create a complete plan for you in seconds. Perfect for students, freelancers, or startups testing ideas before investing in full plans.",
                image: "image4",
                bullets: [
                    "Instant result — ready in seconds",
                    "Customizable tone and structure",
                    "Export to PDF instantly",
                    "Perfect for prototypes, pitches, or early drafts",
                ],
            },
        },

        // 🖼️ GRID — Visuals
        {
            type: "grid",
            columns: 3,
            gap: "1rem",
            cards: [
                {
                    image: "image3",
                    title: "Executive Summary Example",
                    description:
                        "A clear and concise overview investors love — written by experts or generated by AI.",
                },
                {
                    image: "image5",
                    title: "Financial Forecast Section",
                    description:
                        "Smart, easy-to-understand charts and projections that make your numbers look professional.",
                },
                {
                    image: "image6",
                    title: "Beautiful PDF Layouts",
                    description:
                        "Minimal and modern layouts ready to print or send directly to investors.",
                },
            ],
        },

        // 🎬 VIDEO DEMO
        {
            type: "custom",
            component: "VideoDemo",
            title: "See How It Works",
            description: `Watch how ${COMPANY_NAME} turns your business idea into a full, structured plan — step by step, from concept to a polished investor-ready document.`,
            video: "planDemo",
        },

        // 💡 VALUES ICONS
        {
            type: "custom",
            component: "ValuesIcons",
            title: `Why Entrepreneurs Love ${COMPANY_NAME}`,
            description:
                "We simplify business planning with a friendly experience, reliable results, and options for every goal. No corporate jargon — just clarity and quality.",
            values: [
                {
                    icon: "🧠",
                    title: "Smart + Simple",
                    text: "A guided form that helps you describe your business naturally.",
                },
                {
                    icon: "💼",
                    title: "Professional Results",
                    text: "Plans formatted and structured for investors, banks, or presentations.",
                },
                {
                    icon: "⚙️",
                    title: "Customizable Output",
                    text: "Choose your tone, language, and modules to match your needs.",
                },
                {
                    icon: "💬",
                    title: "Real Human Touch",
                    text: "Get direct support and optional expert reviews for guaranteed quality.",
                },
            ],
        },

        // 🪜 TIMELINE — 24h Plan Process
        {
            type: "custom",
            component: "Timeline",
            title: "How the 24-Hour Plan Works",
            steps: [
                {
                    title: "1. Submit Your Idea",
                    description:
                        "Fill out a simple form about your business goals, audience, and product.",
                },
                {
                    title: "2. Expert Review",
                    description:
                        "A real business writer reviews your details and defines the best structure.",
                },
                {
                    title: "3. Research & Writing",
                    description:
                        "We analyze your market, build forecasts, and create a tailored plan.",
                },
                {
                    title: "4. Final Quality Check",
                    description:
                        "Every plan is double-checked for clarity, accuracy, and investor appeal.",
                },
                {
                    title: "5. Delivery in 24h",
                    description:
                        "Receive your editable, professional business plan — ready to share or pitch.",
                },
            ],
        },

        // 🧱 GRID — Use cases
        {
            type: "grid",
            columns: 3,
            gap: "1.5rem",
            cards: [
                {
                    image: "image7",
                    title: "Startup Founders",
                    description:
                        "Launch your vision with a clear, data-driven business plan that investors take seriously.",
                },
                {
                    image: "image8",
                    title: "Students & Educators",
                    description:
                        "Create business plans for class projects, competitions, or thesis work in minutes.",
                },
                {
                    image: "image9",
                    title: "Freelancers & Consultants",
                    description:
                        "Offer professional business planning services with our AI or expert support.",
                },
            ],
        },

        // 🧮 PRICING — Plans
        {
            type: "grid",
            columns: 3,
            gap: "2rem",
            cards: [
                {
                    type: "pricing",
                    variant: "starter",
                    title: "AI Instant Plan",
                    price: "€9",
                    tokens: 900,
                    badgeTop: "Instant",
                    description:
                        "Generate your business plan in seconds with our AI-powered generator. Perfect for quick ideas or early drafts.",
                    features: [
                        "Instant generation",
                        "Editable format",
                        "Multiple languages",
                        "Unlimited revisions",
                    ],
                    buttonText: "Start with AI",
                    buttonLink: "/checkout?plan=ai",
                },
                {
                    type: "pricing",
                    variant: "pro",
                    title: "Expert 24h Plan",
                    price: "€20",
                    tokens: 2000,
                    badgeTop: "24-Hour Delivery",
                    description:
                        "Get a complete, investor-ready business plan written and reviewed by professionals within 24 hours.",
                    features: [
                        "Market & competitor analysis",
                        "3-year financial forecast",
                        "Editable PDF & DOCX",
                        "Personal revision support",
                    ],
                    buttonText: "Order Expert Plan",
                    buttonLink: "/checkout?plan=expert",
                },
                {
                    type: "pricing",
                    variant: "premium",
                    title: "Investor Pack",
                    price: "€50",
                    tokens: 5000,
                    badgeTop: "Complete Package",
                    description:
                        "All-in-one: full business plan + investor pitch deck + design layout. Ideal for fundraising and presentations.",
                    features: [
                        "Business plan + Pitch deck",
                        "Branded design templates",
                        "Investor-ready presentation",
                        "Expert revisions included",
                    ],
                    buttonText: "Get Full Pack",
                    buttonLink: "/checkout?plan=premium",
                },
            ],
        },

        // 🧩 Custom Plan section
        {
            type: "section",
            title: "Need something custom?",
            description: "We can tailor a package for your exact goals.",
            left: {
                type: "custom",
                component: "InfoBlock",
                title: "Custom Plan for You",
                description:
                    "Mix and match AI writing, expert review, and design assistance for a bespoke experience.",
                bullets: ["Flexible scope", "Personal contact", "Dynamic pricing"],
            },
            right: {
                type: "pricing",
                variant: "custom",
                title: "Custom Plan",
                price: "dynamic",
                tokens: 0,
                badgeTop: "Flexible",
                description: "Enter your budget, and we’ll match the right solution.",
                features: ["Flexible pricing", "Mix AI & Expert", "Fast setup"],
                buttonText: "Create Your Plan",
                buttonLink: "/checkout?plan=custom",
            },
        },

        // 👥 WHO IT’S FOR
        {
            type: "section",
            title: `Who Uses ${COMPANY_NAME}`,
            left: {
                type: "media",
                mediaType: "image",
                src: "image10",
            },
            right: {
                type: "text",
                title: "From Students to Startups",
                description: `Whether you're preparing a pitch for investors, a project for university, or a proposal for clients — ${COMPANY_NAME} helps you create structured, beautiful plans fast. You focus on your idea; we take care of the rest.`,
            },
        },

        // ⭐ TESTIMONIALS
        {
            type: "custom",
            component: "TestimonialsSlider",
            title: "What Our Users Say",
            description: `Thousands of entrepreneurs, students, and consultants use ${COMPANY_NAME} to save time and impress investors. Here’s what they think:`,
            testimonials: [
                {
                    name: "Marta Lopez",
                    role: "Startup Founder",
                    image: "review1",
                    text: "I got my expert plan in 24 hours — complete, professional, and ready to pitch. It helped me secure my first investment!",
                    rating: 5,
                },
                {
                    name: "Jonas Richter",
                    role: "MBA Student",
                    image: "review2",
                    text: "The AI generator was surprisingly good. It gave me a solid structure that made my business plan presentation a breeze.",
                    rating: 5,
                },
                {
                    name: "Claire Wang",
                    role: "Investor Relations Manager",
                    image: "review3",
                    text: "I’ve seen many startup plans — but these are truly investor-ready. The visuals and structure are top-notch.",
                    rating: 5,
                },{
                    name: "Marta Lopez",
                    role: "Startup Founder",
                    image: "review1",
                    text: "I got my expert plan in 24 hours — complete, professional, and ready to pitch. It helped me secure my first investment!",
                    rating: 5,
                },
                {
                    name: "Jonas Richter",
                    role: "MBA Student",
                    image: "review2",
                    text: "The AI generator was surprisingly good. It gave me a solid structure that made my business plan presentation a breeze.",
                    rating: 5,
                },
                {
                    name: "Claire Wang",
                    role: "Investor Relations Manager",
                    image: "review3",
                    text: "I’ve seen many startup plans — but these are truly investor-ready. The visuals and structure are top-notch.",
                    rating: 5,
                },
            ],
        },

        // ❓ FAQ
        {
            type: "faq",
            items: [
                {
                    question: "How fast will I receive my expert-written plan?",
                    answer:
                        "All expert plans are delivered within 24 hours after you submit your details and payment. You’ll receive editable files by email.",
                },
                {
                    question: "Is the AI plan editable?",
                    answer:
                        "Yes! You can edit, regenerate, and adjust every section as many times as you like before exporting.",
                },
                {
                    question: "Do both plans include financial projections?",
                    answer:
                        "Yes, both options include 3-year financial projections and pre-built tables for easy editing.",
                },
                {
                    question: "Is my business idea private?",
                    answer:
                        "Absolutely. We use encrypted storage and never share your data with third parties. Your content is 100% confidential.",
                },
            ],
        },

        // 🎯 FINAL CTA
        {
            type: "custom",
            component: "MissionBanner",
            title: "Start Your Business Plan Today",
            description: `Whether you need expert help or instant AI results, ${COMPANY_NAME} is the fastest way to turn your ideas into a professional business plan. Let’s make your vision real — starting now.`,
            image: "image11",
        },

        // 📩 CONTACT FORM
        {
            type: "custom",
            component: "ContactForm",
            title: "Need Help Choosing?",
            description:
                "Not sure whether to go with the expert plan or AI version? Message us — our support team will help you find the perfect fit.",
        },
    ],
};

export default schema;
